# Generated by Django 4.0.5 on 2022-12-22 06:33

from django.db import migrations, models
import students.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='application_no',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='registration_no',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_pix',
            field=models.ImageField(upload_to=students.models.student_directory_path),
        ),
    ]
