# Generated by Django 4.1.4 on 2022-12-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_application_no_student_registration_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='application_no',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
