# Generated by Django 4.1.6 on 2023-04-10 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_application_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='profile_pix',
            new_name='profile_pic',
        ),
    ]
