# Generated by Django 4.1.4 on 2022-12-24 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_application_no'),
        ('screening', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondscreening',
            name='first_screening',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='first_screening', to='screening.firstscreening'),
        ),
        migrations.AlterField(
            model_name='firstscreening',
            name='comment',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='firstscreening',
            name='dateApproved',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='firstscreening',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('pending for record officer', 'pending for record officer'), ('pending for student affair', 'pending for student affair'), ('approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='secondscreening',
            name='dateApproved',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='secondscreening',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('pending for record officer', 'pending for record officer'), ('pending for student affair', 'pending for student affair'), ('approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='secondscreening',
            name='student_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='students.student'),
        ),
    ]
