# Generated by Django 4.1.4 on 2022-12-24 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0002_secondscreening_first_screening_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondscreening',
            name='first_screening',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='first_screening', to='screening.firstscreening'),
        ),
    ]
