# Generated by Django 4.1.4 on 2022-12-25 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_application_no'),
        ('screening', '0003_alter_secondscreening_first_screening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondscreening',
            name='student_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
