# Generated by Django 4.1.6 on 2023-04-05 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_affair_officers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentaffairofficer',
            name='department_id',
        ),
    ]
