# Generated by Django 4.1.4 on 2022-12-21 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('record_officer', 'Record Officer'), ('student_affair', 'Student Affair Officer')], default='student', max_length=30),
        ),
    ]
