# Generated by Django 4.1.4 on 2022-12-25 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import record_officers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0003_alter_student_application_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to=record_officers.models.avatar_directory_path)),
                ('phone_no', models.CharField(max_length=11)),
                ('department_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.department')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
